sudo: false
language: generic
env:
  global:
    - PKG_NAME="pdbx-mmcif"
    - SRC_DIR="${TRAVIS_BUILD_DIR}"
    - TEST_DIR="${HOME}/_test"
install:
  # Install Anaconda
  - wget --no-verbose -O anaconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh;
  - bash anaconda.sh -b -p $HOME/anaconda
  - export PATH="$HOME/anaconda/bin:$PATH"
  - hash -r
  # Add relevant channels
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - conda config --add channels omnia
  - conda info -a
  # Install packages
  - conda update -q conda
  - conda install -q --yes conda-build
  # Build package
  # - conda build devtools/conda-recipe/
  - python setup.py develop
script:
  # Run tests
  - pip install 'pytest >3' pytest-runner pytest-cov pytest-logging flake8
  - flake8
after_success:
  - echo "Success!"
  - pip install codecov
  - codecov
  - |
    if [[ $TEST_SUITE == 'test_unittests' && \
          $TRAVIS_BRANCH = "master" && \
          $TRAVIS_PULL_REQUEST = false ]] ; then
        echo "Uploading to binstar..."
        conda install -q --yes anaconda-client
        anaconda -t ANACONDA_TOKEN upload /home/travis/anaconda/conda-bld/linux-64/*.tar.bz2
    fi
after_failure:
  - echo "Failure!"
after_script:
  # - ${SCRIPTS_DIR}/cleanup_test.sh
  - echo "X_X"
